- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep eduphpapp | wc -l` -gt 0 ]; then  
            kubectl delete deploy `kubectl get deploy | grep -v NAME | awk '{print $1}' | grep eduphpapp`
         else 
            echo "No app deployments found"
         fi
         if [ `kubectl get svc | grep eduphpapp-svc  | awk '{print $1}' | wc -l` -gt 0 ]; then
            kubectl delete svc `kubectl get svc | grep eduphpapp-svc | awk '{print $1}'`
         else
            echo "No app service found"
         fi
    - name: deploy app
      command: kubectl create deploy eduphpapp --image=webhostatwork/projectcert_devops:{{ build }}
    - name: increase replicas 
      command: kubectl scale deploy eduphpapp --replicas=2
    - name: deploy service
      command: kubectl expose deploy eduphpapp --name eduphpapp-svc --port 8080 --type NodePort
